.de Ip
.br
.ie \\n.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.\"
.TH COMPILER467 1 "September 2009" "CSC467F MiniGLSL Compiler"
.SH NAME
compiler467 \- a compiler for the CSC467F Project MiniGLSL Language
.SH SYNOPSIS
.in +\w'\fBcompiler467 \fR'u
.ti -\w'\fBcompiler467 \fR'u
.B compiler467 
[\fB\-X\fR] [\fB\-D\fR[\fIasxy\fR]] [\fB\-T\fR[\fInpx\fR]] [\fB\-O\fR\ \fIoutputfile\fR\]
.br
[\fB\-E\fR\ \fIerrorfile\fR\] [\fB\-R\fR\ \fItracefile\fR\] [\fB\-U\fR\ \fIdumpfile\fR\]
.br
[\fB\-I\fR\ \fIruninputfile\fR\] [\fIsourcefile\fR\]
.br
.SH DESCRIPTION
.B compiler467
is an incredibly well designed and implemented compiler for the
CSC467F Course Project MiniGLSL Language.
.PP
The compiler compiles and then attempts to execute one program
written in MiniGLSL.
The compiler reads the source program from \fIsourceFile\fR
if it was specified in the command that invoked the compiler.
Otherwise it expects the source program on standard input.
.SH OPTIONS
The options currently implemented by the
compiler467 are:
.TP 12
.BR \-X
Suppress execution of the compiled program.  Saves time when testing
an incomplete code generator.
.TP
.BR \-D
Specify dump options.  The letters \fIasxy\fR indicate which information
should be dumped to the compilers \fIdumpFile\fR.
.RS
\fIa\fR \- dump the abstract syntax tree
.br
\fIs\fR \- dump the source code (with line numbers)
.br
\fIx\fR \- dump the compiled code just before execution
.br
\fIy\fR \- dump symbol table information
.RE
.TP
.BR \-T
Specify trace options.  The letters \fInpx\fR indicate which trace
information
should be written to the compilers \fItraceFile\fR.
.RS
\fIn\fR \- trace scanning
.br
\fIp\fR \- trace parsing
.br
\fIx\fR \- trace program execution
.RE
.TP 12
.BR \-E \ \ \ \fIerrorFile\fR
Specify an alternative file to receive error messages generated by the compiler.
Default for error messages is stderr.
.TP
.BI \-O \ \ \ \fIoutputFileName\fR
Specify an alternative file to receive ordinary compiler output (includes
compilation and execution). Default is stdout
.TP
.BR \-R \ \ \ \fItraceFileName\fR
Specify an alternative file to receive compiler trace information.
Default for trace information is stdout.
.TP
.BR \-U \ \ \ \fIdumpFileName\fR
Specify an alternative file to receive compiler dump information.
Default for dump information is stdout.
.TP
.BR \-I \ \ \ \fIrunInputFileName\fR
Specify an alternative file to serve as a source of input during
execution of the compiled program.
Default for execution time input is stdin.
.SH ENVIRONMENT
The compiler does not use any Unix environment variables.
.SH AUTHORS
The 
.B MiniGLSL Compiler
was implimented by eugene miretsky
.SH BUGS
There are none; only a few unexpected features.
